version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.0

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci

  lint:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run: npx eslint . --ext .js,.jsx,.ts,.tsx

  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run: npm run test

  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run: npm run build

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run:
          name: Deploy to Netlify
          command: |
            npx netlify deploy --prod --dir=out --auth=${NETLIFY_AUTH_TOKEN} --site=${NETLIFY_SITE_ID}


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
